In [1]:
import syft as sy
import torch as th
from syft.frameworks.torch.he.fv import keygen, encrypt, decrypt
hook = sy.TorchHook(th)

In [2]:
key = keygen()

In [7]:
SK = key[0]
SK

array([504858, 177343, 383671, 339809, 533774,  63166,  79456, 551032,
        94718,  79100, 266074, 474094, 186329, 242313, 314634, 251274,
       507524, 578890, 565295,      1])

In [8]:
PK = key[1]
PK

array([[229685, 173261, 147775, ..., 320031, 270647, 538638],
       [148766, 558803, 252373, ..., 525872, 404031, 210748],
       [583158, 568758, 570324, ...,  78998, 412124, 227489],
       ...,
       [226538, 568910, 367017, ..., 440381, 587180, 257520],
       [264579, 500143, 552755, ..., 492739, 510572,  18165],
       [293540, 471706,  99966, ..., 205864, 249429, 362090]])

In [9]:
message = 6
ct = encrypt(key.PK,message)

AttributeError: 'list' object has no attribute 'PK'

In [7]:
ct

[array([7., 7., 7., 7., 7., 7., 8., 6., 8., 6., 7., 8., 8., 7., 8., 6., 7.,
        7., 8., 7.]),
 array([11.,  0.,  1.,  8., 13.])]

In [8]:
dt = decrypt(sec,ct)

In [9]:
dt

array([9., 9., 9., 9., 9., 9., 9., 8., 9., 8., 9., 9., 9., 9., 9., 8., 9.,
       9., 9., 9.])